### ISSUE TITLE
Crash/bug

### ISSUE THREAD

**Issue by Moobien** [Domochevsky/minecraft-gentleharvest#2]
Getting a crash. Raised it with the Industrial Foregoing guys snd they suspect it could be Gentle Harvest.

https://github.com/Buuz135/Industrial-Foregoing/issues/227

**Comment by Domochevsky** [comment]
Hm...

`java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in BlockStateContainer{block=harvestcraft:pamparsnipcrop, properties=[age]}`

**block=harvestcraft:pamparsnipcrop** <- that seems to be the block that causes Gentle Harvest to stumble, by unexpectedly not having an age property despite being a crop.

So the key person to talk to would be the maker of HarvestCraft. What we could do _here_, however, is add a bit of hardening, so it doesn't outright fall over when encountering such a thing.

Maybe surround `int age = blockState.getValue(property);` in Event_Listener.java line 125 with ...um, why is that crashing anyway? Just because the property doesn't exist doesn't mean that Minecraft has to explode. Just return 0 or some other default. Someone coded it to be like this. o_O

Either way, a try/catch would solve that on our end. Catch and just not touch the block if it has no age, since it probably doesn't want to be messed with.

**Comment by Moobien** [comment]
The crashes started when i powered up a IF Plant Interactor

**Comment by EPIICTHUNDERCAT** [comment]
@Moobien yep, thats cus of what he said, block=harvestcraft:pamparsnipcrop is not made correctly / made different, which causes what we do, which ShOuLdNt break, break. so now I need to update it just cus one mod can do things correctly :P.

**Comment by EPIICTHUNDERCAT** [comment]
ill work on this when i get the time. for now i suggest u remove that crop.

**Comment by Moobien** [comment]
Ok :)

**Comment by ghost** [comment]
To the OP;
I have encountered this issue also; I had fixed it by checking out what mods were installed- turns out I installed SimpleHarvest + GentleHarvest and that was conflicting against each other.
Hope this helps.

**Comment by ghost** [comment]
After reviewing this further, the same issue encounters with ChocoCraft 3.
I hope the developer finds a fix.

**Comment by Domochevsky** [comment]
Fixed in #4
